/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simple_ndk_wxelife_com_ndksimple_NdkHelper */

#ifndef _Included_simple_ndk_wxelife_com_ndksimple_NdkHelper
#define _Included_simple_ndk_wxelife_com_ndksimple_NdkHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simple_ndk_wxelife_com_ndksimple_NdkHelper
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_simple_ndk_wxelife_com_androidndk_MainActivity_getCLanguageString
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_simple_ndk_wxelife_com_androidndk_MainActivity_nativeInit
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_simple_ndk_wxelife_com_androidndk_MainActivity_nativeFree
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_simple_ndk_wxelife_com_androidndk_MainActivity_nativeWorker
  (JNIEnv *, jobject,jint ,jint);

JNIEXPORT void JNICALL Java_simple_ndk_wxelife_com_androidndk_MainActivity_nativeWThreads
  (JNIEnv *, jobject,jint ,jint);

#ifdef __cplusplus
}
#endif
#endif
